### ISSUE TITLE
在你的博客上面留了点问题，麻烦帮我看看啊

### ISSUE THREAD

**Issue by bethinner** [linfaxin/AndroidUI-WebApp#1]
http://linfaxin.com/2016/01/20/%E8%BD%AC%E6%88%98WebApp-%E6%9C%80%E9%80%82%E5%90%88Android%E5%BC%80%E5%8F%91%E8%80%85%E7%9A%84WebApp%E6%A1%86%E6%9E%B6/

/StormProject/AndroidUI4Web-HelloWorld-master/androidui-sdk/android-ui.d.ts
Error:(667, 14) TS1005: ';' expected.
这是编码的问题，还是什么问题啊？

另外提示我当前版本的javaScript不支持Classes 用的是EcmaScript, 另外还有一些版本，但是不知道用哪个，好像别的不支持相应的浏览器的意思，只会写android的小白求指教

**Comment by linfaxin** [comment]
试试：Preferences -> Languages & Frameworks -> JavaScript -> 选择EcmaScript6

**Comment by bethinner** [comment]
改了这个好像是可以了但是，还是会报android-ui.d.ts下面，Error:(667, 14) TS1005: ';' expected.
查了一下别的人也有类似的问题，都是说tsc版本过低，但是我这边都是最新了。后来有个人发了他的信息：
$ tsc -v
message TS6029: Version 1.4.1.0（我的是message TS6029: Version 1.7.5）

$ npm -v
2.14.7  （我的是2.14.12）

$ node -v
v4.2.1  （我的是v4.2.6）

$ tsd --version

> > tsd 0.6.5 （我的是command not found）

我发现我是没有最后一个的，我是不是少安装了什么东西

**Comment by linfaxin** [comment]
@bethinner 进QQ群来：275850460，我细看一下。
