### ISSUE TITLE
运行 androidui create 出错

### ISSUE THREAD

**Issue by KalSat** [linfaxin/AndroidUI-WebApp#8]
C:\Users\chengbiao\WebstormProjects\auix-demo>androidui create

downloading templates...
downloading project dependencies...
build project...
{ Error: ENOENT: no such file or directory, stat 'C:\Users\chengbiao\WebstormProjects\auix-demo\node_modules\androiduix\dist'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at Object.statSync (C:\Users\chengbiao\AppData\Roaming\npm\node_modules\androidui-cli\node_modules\graceful-fs\polyfills.js:297:22)
    at Object.copySync (C:\Users\chengbiao\AppData\Roaming\npm\node_modules\androidui-cli\node_modules\fs-extra\lib\copy-sync\copy-sync.js:20:58)
    at C:\Users\chengbiao\AppData\Roaming\npm\node_modules\androidui-cli\index.js:39:21
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\chengbiao\\WebstormProjects\\auix-demo\\node_modules\\androiduix\\dist' }
exec error: Error: Command failed: npm run build
npm WARN auix-demo No description
module.js:471
    throw err;
    ^

Error: Cannot find module 'jsdom'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\chengbiao\WebstormProjects\auix-demo\build_res.js:6:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chengbiao\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-res"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ build-res: `echo 'building resource...' && node build_res.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build-res script 'echo 'building resource...' && node build_res.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     echo 'building resource...' && node build_res.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\chengbiao\WebstormProjects\auix-demo\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chengbiao\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ build: `npm run build-install && npm run build-res && npm run build-ts2js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script 'npm run build-install && npm run build-res && npm run build-ts2js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-install && npm run build-res && npm run build-ts2js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\chengbiao\WebstormProjects\auix-demo\npm-debug.log

stderr:
npm WARN auix-demo No description
module.js:471
    throw err;
    ^

Error: Cannot find module 'jsdom'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\chengbiao\WebstormProjects\auix-demo\build_res.js:6:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chengbiao\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-res"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ build-res: `echo 'building resource...' && node build_res.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build-res script 'echo 'building resource...' && node build_res.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     echo 'building resource...' && node build_res.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\chengbiao\WebstormProjects\auix-demo\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chengbiao\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @ build: `npm run build-install && npm run build-res && npm run build-ts2js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script 'npm run build-install && npm run build-res && npm run build-ts2js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-install && npm run build-res && npm run build-ts2js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\chengbiao\WebstormProjects\auix-demo\npm-debug.log

stdout:

> @ build C:\Users\chengbiao\WebstormProjects\auix-demo
> npm run build-install && npm run build-res && npm run build-ts2js

> @ build-install C:\Users\chengbiao\WebstormProjects\auix-demo
> echo 'installing dependencies...' && npm install --registry=https://registry.npm.taobao.org

'installing dependencies...'

> @ build-res C:\Users\chengbiao\WebstormProjects\auix-demo
> echo 'building resource...' && node build_res.js

'building resource...'

**Comment by linfaxin** [comment]
一般是网络原因导致的 npm 依赖下载失败，建议重试

**Comment by KalSat** [comment]
不知道为什么npm install没有安装所有依赖，我手动安装一遍依赖，现在卡在build-ts2js这一步。
log如下：
"C:\Program Files (x86)\WebStorm\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run build

> auix-demo@1.0.0 build C:\Users\chengbiao\WebstormProjects\auix-demo
> npm run build-install && npm run build-res && npm run build-ts2js


> auix-demo@1.0.0 build-install C:\Users\chengbiao\WebstormProjects\auix-demo
> echo 'installing dependencies...' && npm install --registry=https://registry.npm.taobao.org

'installing dependencies...' 

> auix-demo@1.0.0 build-res C:\Users\chengbiao\WebstormProjects\auix-demo
> echo 'building resource...' && node build_res.js

'building resource...' 

> auix-demo@1.0.0 build-ts2js C:\Users\chengbiao\WebstormProjects\auix-demo
> echo 'converting TypeScript to JS...' && "node_modules/.bin/tsc" -p ./

'converting TypeScript to JS...' 
src/MainActivity.ts(1,12): error TS1005: '>' expected.
src/MainActivity.ts(1,16): error TS1005: ';' expected.
src/MainActivity.ts(1,52): error TS1109: Expression expected.
src/MainActivity.ts(2,12): error TS1005: '>' expected.
src/MainActivity.ts(2,16): error TS1005: ';' expected.
src/MainActivity.ts(2,31): error TS1109: Expression expected.
src/MainActivity.ts(4,8): error TS1005: ';' expected.
src/MainActivity.ts(4,15): error TS1005: ';' expected.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chengbiao\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-ts2js"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! auix-demo@1.0.0 build-ts2js: `echo 'converting TypeScript to JS...' && "node_modules/.bin/tsc" -p ./`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the auix-demo@1.0.0 build-ts2js script 'echo 'converting TypeScript to JS...' && "node_modules/.bin/tsc" -p ./'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the auix-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     echo 'converting TypeScript to JS...' && "node_modules/.bin/tsc" -p ./
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs auix-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls auix-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\chengbiao\WebstormProjects\auix-demo\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! auix-demo@1.0.0 build: `npm run build-install && npm run build-res && npm run build-ts2js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the auix-demo@1.0.0 build script 'npm run build-install && npm run build-res && npm run build-ts2js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the auix-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-install && npm run build-res && npm run build-ts2js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs auix-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls auix-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\chengbiao\WebstormProjects\auix-demo\npm-debug.log

Process finished with exit code 1

**Comment by KalSat** [comment]
谢谢，手动安装依赖可解决问题。
npm install --save-dev jsdom typescript
